basePath: /api/v1
definitions:
  model.BroadCastUpdateInput:
    properties:
      broadcastPosition:
        type: string
      broadcastText:
        type: string
      channelId:
        type: string
      endTime:
        type: string
      gameId:
        type: integer
      gameVersion:
        type: string
      id:
        type: integer
      partnerId:
        type: string
      startTime:
        type: string
      worldId:
        type: string
    type: object
  model.OssForm:
    properties:
      checksum:
        type: string
      content:
        type: string
    type: object
  model.PageResult:
    properties:
      pageIndex:
        description: 页签
        type: integer
      pageSize:
        description: 页码
        type: integer
      result:
        description: 结果
      total:
        description: 总条数
        type: integer
    type: object
  model.ResponseResult:
    properties:
      code:
        description: 状态
        type: integer
      msg:
        description: 消息
        type: string
      result:
        description: 结果
    type: object
info:
  contact: {}
  description: IvanApi Service
  title: IvanApi Swagger
  version: "1.0"
paths:
  /login:
    get:
      consumes:
      - application/json
      description: login
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      - description: name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseResult'
      summary: 登录
      tags:
      - login
  /ops/broadcast:
    delete:
      consumes:
      - application/json
      description: delete
      parameters:
      - description: Id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseResult'
      summary: 删除
      tags:
      - ops
    post:
      consumes:
      - application/json
      description: update
      parameters:
      - description: 信息
        in: body
        name: broadInput
        required: true
        schema:
          $ref: '#/definitions/model.BroadCastUpdateInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseResult'
      summary: 新增
      tags:
      - ops
    put:
      consumes:
      - application/json
      description: update
      parameters:
      - description: 入参
        in: body
        name: broadInput
        required: true
        schema:
          $ref: '#/definitions/model.BroadCastUpdateInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseResult'
      summary: 修改
      tags:
      - ops
  /ops/getbroadcast:
    get:
      consumes:
      - application/json
      description: get users
      parameters:
      - description: 游戏Id
        in: query
        name: gameId
        required: true
        type: integer
      - description: 游戏版本
        in: query
        name: gameVersion
        required: true
        type: string
      - description: pageIndex
        in: query
        name: pageIndex
        required: true
        type: integer
      - description: pageSize
        in: query
        name: pageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PageResult'
      summary: 获取广播
      tags:
      - ops
  /oss/callback:
    post:
      consumes:
      - application/json
      description: oss callback
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.OssForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: oss callback
      tags:
      - oss
  /test:
    get:
      consumes:
      - application/json
      description: test
      parameters:
      - description: 验证头
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 测试
      tags:
      - test
  /test/fifth:
    get:
      consumes:
      - application/json
      description: test4
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 测试4
      tags:
      - test
  /test/second:
    get:
      consumes:
      - application/json
      description: test2
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 测试2
      tags:
      - test
  /test/third:
    get:
      consumes:
      - application/json
      description: test3
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 测试3
      tags:
      - test
swagger: "2.0"
