basePath: /api/v1
definitions:
  Model.PageResult:
    properties:
      pageIndex:
        description: 页签
        type: integer
      pageSize:
        description: 页码
        type: integer
      result:
        description: 结果
      total:
        description: 总条数
        type: integer
    type: object
info:
  contact: {}
  description: IvanApi Service
  title: IvanApi Swagger
  version: "1.0"
paths:
  /ops/getbroadcast:
    get:
      consumes:
      - application/json
      description: get users
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 游戏Id
        in: query
        name: gameId
        required: true
        type: integer
      - description: 游戏版本
        in: query
        name: gameVersion
        required: true
        type: string
      - description: pageIndex
        in: query
        name: pageIndex
        required: true
        type: integer
      - description: pageSize
        in: query
        name: pageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Model.PageResult'
      summary: 获取广播
      tags:
      - ops
swagger: "2.0"
